[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/server/**/*", ".next/standalone/**/*"]
  node_bundler = "esbuild"

[[edge_functions]]
  function = "form"
  path = "/api/form"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_netlify_forms/:splat"
  status = 200
  force = true
  conditions = {X-Netlify-Form = "true"} 