export const WHBAR_ID = process.env.NEXT_PUBLIC_WHBAR_HEDERA_ID as string;
export const WHBAR_EVM_ADDRESS = process.env.NEXT_PUBLIC_WHBAR_EVM_ADDRESS as string;
export const QUOTER_V2_ADDRESS = process.env.NEXT_PUBLIC_QUOTER_V2_ADDRESS as string;
export const SWAP_ROUTER_ADDRESS = process.env.NEXT_PUBLIC_SWAP_ROUTER_ADDRESS as string;
export const SAUCERSWAP_FACTORY_ADDRESS = process.env.NEXT_PUBLIC_SAUCERSWAP_FACTORY_ADDRESS!;
export const SAUCERSWAP_QUOTER_ADDRESS = process.env.NEXT_PUBLIC_QUOTER_V2_ADDRESS!;
export const SAUCERSWAP_ROUTER_ADDRESS = process.env.NEXT_PUBLIC_SWAP_ROUTER_ADDRESS!; 