/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHederaTokenService,
  IHederaTokenServiceInterface,
} from "../../../../../src/app/contracts/LynxMinter.sol/IHederaTokenService";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "associateToken",
    outputs: [
      {
        internalType: "int256",
        name: "responseCode",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "isTokenAssociated",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHederaTokenService__factory {
  static readonly abi = _abi;
  static createInterface(): IHederaTokenServiceInterface {
    return new Interface(_abi) as IHederaTokenServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHederaTokenService {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHederaTokenService;
  }
}
