/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISaucerSwapV2SwapRouter,
  ISaucerSwapV2SwapRouterInterface,
} from "../../../../../src/app/contracts/userThreshold.sol/ISaucerSwapV2SwapRouter";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "path",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMinimum",
            type: "uint256",
          },
        ],
        internalType: "struct ISaucerSwapV2SwapRouter.ExactInputParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "exactInput",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "refundETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISaucerSwapV2SwapRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ISaucerSwapV2SwapRouterInterface {
    return new Interface(_abi) as ISaucerSwapV2SwapRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISaucerSwapV2SwapRouter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISaucerSwapV2SwapRouter;
  }
}
