/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface NFTSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentTokenId"
      | "getPurchaseState"
      | "hasPurchased"
      | "maxSupply"
      | "owner"
      | "price"
      | "purchaseNFT"
      | "soldSupply"
      | "tokenAddress"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Debug"
      | "NFTSold"
      | "PaymentDebug"
      | "PaymentForwarded"
      | "PaymentReceived"
      | "PurchaseInitiated"
      | "StateChange"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "currentTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPurchaseState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "maxSupply", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "price", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "soldSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "currentTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPurchaseState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxSupply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "soldSupply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace DebugEvent {
  export type InputTuple = [
    message: string,
    sender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [message: string, sender: string, value: bigint];
  export interface OutputObject {
    message: string;
    sender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTSoldEvent {
  export type InputTuple = [buyer: AddressLike, serialNumber: BigNumberish];
  export type OutputTuple = [buyer: string, serialNumber: bigint];
  export interface OutputObject {
    buyer: string;
    serialNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentDebugEvent {
  export type InputTuple = [
    message: string,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    message: string,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    message: string;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentForwardedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReceivedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PurchaseInitiatedEvent {
  export type InputTuple = [buyer: AddressLike, value: BigNumberish];
  export type OutputTuple = [buyer: string, value: bigint];
  export interface OutputObject {
    buyer: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateChangeEvent {
  export type InputTuple = [
    operation: string,
    tokenId: BigNumberish,
    newSoldSupply: BigNumberish
  ];
  export type OutputTuple = [
    operation: string,
    tokenId: bigint,
    newSoldSupply: bigint
  ];
  export interface OutputObject {
    operation: string;
    tokenId: bigint;
    newSoldSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NFTSale extends BaseContract {
  connect(runner?: ContractRunner | null): NFTSale;
  waitForDeployment(): Promise<this>;

  interface: NFTSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentTokenId: TypedContractMethod<[], [bigint], "view">;

  getPurchaseState: TypedContractMethod<
    [buyer: AddressLike],
    [
      [boolean, bigint, bigint] & {
        purchased: boolean;
        nextToken: bigint;
        remaining: bigint;
      }
    ],
    "view"
  >;

  hasPurchased: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  maxSupply: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  price: TypedContractMethod<[], [bigint], "view">;

  purchaseNFT: TypedContractMethod<[], [void], "payable">;

  soldSupply: TypedContractMethod<[], [bigint], "view">;

  tokenAddress: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPurchaseState"
  ): TypedContractMethod<
    [buyer: AddressLike],
    [
      [boolean, bigint, bigint] & {
        purchased: boolean;
        nextToken: bigint;
        remaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseNFT"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "soldSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Debug"
  ): TypedContractEvent<
    DebugEvent.InputTuple,
    DebugEvent.OutputTuple,
    DebugEvent.OutputObject
  >;
  getEvent(
    key: "NFTSold"
  ): TypedContractEvent<
    NFTSoldEvent.InputTuple,
    NFTSoldEvent.OutputTuple,
    NFTSoldEvent.OutputObject
  >;
  getEvent(
    key: "PaymentDebug"
  ): TypedContractEvent<
    PaymentDebugEvent.InputTuple,
    PaymentDebugEvent.OutputTuple,
    PaymentDebugEvent.OutputObject
  >;
  getEvent(
    key: "PaymentForwarded"
  ): TypedContractEvent<
    PaymentForwardedEvent.InputTuple,
    PaymentForwardedEvent.OutputTuple,
    PaymentForwardedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReceived"
  ): TypedContractEvent<
    PaymentReceivedEvent.InputTuple,
    PaymentReceivedEvent.OutputTuple,
    PaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "PurchaseInitiated"
  ): TypedContractEvent<
    PurchaseInitiatedEvent.InputTuple,
    PurchaseInitiatedEvent.OutputTuple,
    PurchaseInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "StateChange"
  ): TypedContractEvent<
    StateChangeEvent.InputTuple,
    StateChangeEvent.OutputTuple,
    StateChangeEvent.OutputObject
  >;

  filters: {
    "Debug(string,address,uint256)": TypedContractEvent<
      DebugEvent.InputTuple,
      DebugEvent.OutputTuple,
      DebugEvent.OutputObject
    >;
    Debug: TypedContractEvent<
      DebugEvent.InputTuple,
      DebugEvent.OutputTuple,
      DebugEvent.OutputObject
    >;

    "NFTSold(address,uint256)": TypedContractEvent<
      NFTSoldEvent.InputTuple,
      NFTSoldEvent.OutputTuple,
      NFTSoldEvent.OutputObject
    >;
    NFTSold: TypedContractEvent<
      NFTSoldEvent.InputTuple,
      NFTSoldEvent.OutputTuple,
      NFTSoldEvent.OutputObject
    >;

    "PaymentDebug(string,address,address,uint256)": TypedContractEvent<
      PaymentDebugEvent.InputTuple,
      PaymentDebugEvent.OutputTuple,
      PaymentDebugEvent.OutputObject
    >;
    PaymentDebug: TypedContractEvent<
      PaymentDebugEvent.InputTuple,
      PaymentDebugEvent.OutputTuple,
      PaymentDebugEvent.OutputObject
    >;

    "PaymentForwarded(address,uint256)": TypedContractEvent<
      PaymentForwardedEvent.InputTuple,
      PaymentForwardedEvent.OutputTuple,
      PaymentForwardedEvent.OutputObject
    >;
    PaymentForwarded: TypedContractEvent<
      PaymentForwardedEvent.InputTuple,
      PaymentForwardedEvent.OutputTuple,
      PaymentForwardedEvent.OutputObject
    >;

    "PaymentReceived(address,uint256)": TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;
    PaymentReceived: TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;

    "PurchaseInitiated(address,uint256)": TypedContractEvent<
      PurchaseInitiatedEvent.InputTuple,
      PurchaseInitiatedEvent.OutputTuple,
      PurchaseInitiatedEvent.OutputObject
    >;
    PurchaseInitiated: TypedContractEvent<
      PurchaseInitiatedEvent.InputTuple,
      PurchaseInitiatedEvent.OutputTuple,
      PurchaseInitiatedEvent.OutputObject
    >;

    "StateChange(string,uint256,uint256)": TypedContractEvent<
      StateChangeEvent.InputTuple,
      StateChangeEvent.OutputTuple,
      StateChangeEvent.OutputObject
    >;
    StateChange: TypedContractEvent<
      StateChangeEvent.InputTuple,
      StateChangeEvent.OutputTuple,
      StateChangeEvent.OutputObject
    >;
  };
}
