/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lynxMinterSol from "./LynxMinter.sol";
export type { lynxMinterSol };
import type * as userThresholdSol from "./userThreshold.sol";
export type { userThresholdSol };
export type { NFTSale } from "./NFTSale";
